//sine value is generated by the sine function.
//its amplitude is output as a pwm singal at pinOUT.
//the idea is to low-pass this signal to generate a simulated analog output.
//the output signal should be connected to pinIN after filtering, where it's read in.
//then this value is printed together with the computed value over serial.
//this way both signal can be compared in the arduino plotter.
//don't forget to set the right baud rate !

#define pinOUT A0
#define pinIN A1
const double constant = 2*3.1415*1/100;


void setup() {
  Serial.begin(38400);
  pinMode(pinOUT, OUTPUT);
  digitalWrite(pinOUT, LOW);
  pinMode(pinIN, INPUT);
}

void loop() {
  for(int i=0;i<=1023;i++)
  {
    int var = (sin(i*constant)+1)*512;
    analogWrite(pinOUT, var>>2); //value divided by 4
    int sensorValue1 = analogRead(pinIN);
    Serial.print(sensorValue1);
    Serial.print(" ");
    Serial.print(var);
    Serial.print(" ");
    Serial.print(0);  // To freeze the lower limit
    Serial.print(" ");
    Serial.print(1023);  // To freeze the upper limit
    Serial.print(" ");
    Serial.println();
  }
}
